baseURL = "https://raf.sh/"
title = "raf.sh"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
enableEmoji = true
rssLimit = 15

[params]
  prompt = "raf@sh"
  description = "Personal homepage and blog"

  [[params.social]]
    name = "email"
    url  = "mailto:me@raf.sh"
  [[params.social]]
    name = "github"
    url  = "https://github.com/Yayg"
  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/5091340/yayg"
  [[params.social]]
    name = "leetcode"
    url  = "https://leetcode.com/just_raf/"

[languages]
  [languages.fr]
    languageName = "Français"
    languageCode = "fr-fr"
    weight = 1
    [languages.fr.params]
      tagline = "dev, parfois ops, MJ à l'occasion"
    [[languages.fr.menu.main]]
      identifier = "dev-ops"
      name = "Dev&Ops"
      url = "/dev-ops/"
      weight = 10
    [[languages.fr.menu.main]]
      identifier = "dnd"
      name = "D&D"
      url = "/dnd/"
      weight = 20
    [[languages.fr.menu.main]]
      identifier = "phi"
      name = "φ"
      url = "/phi/"
      weight = 30
    [[languages.fr.menu.main]]
      identifier = "about"
      name = "à propos"
      url = "/about/"
      weight = 40

  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 2
    [languages.en.params]
      tagline = "software dev, sometimes ops, occasional GM"
    [[languages.en.menu.main]]
      identifier = "dev-ops"
      name = "Dev&Ops"
      url = "/dev-ops/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "dnd"
      name = "D&D"
      url = "/dnd/"
      weight = 20
    [[languages.en.menu.main]]
      identifier = "phi"
      name = "φ"
      url = "/phi/"
      weight = 30
    [[languages.en.menu.main]]
      identifier = "about"
      name = "about"
      url = "/about/"
      weight = 40

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
